runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'FUCO-DBZ'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'qJ@>*q.p`&{;@VUS'
  INSTANCE_CONNECTION_NAME: 'fuco-app1:us-central1:fuco-app'

beta_settings:
  cloud_sql_instances: 'fuco-app1:us-central1:fuco-app'
